console.log(JSON.parse("[{\"HighlightId\":\"2D075BEC-EE07-4078-6342-08DD2FDE285A\",\"HighlightName_EN\":\"Product Backlog Creation Done\",\"HighlightName_AR\":\"Product Backlog Creation Done\",\"HighlightCreatedAt\":\"2025-01-08T17:15:36.2579752\",\"HighlightContent_EN\":\"The Product backlog document has been created and passed to the UI Department to create aa UI With the features that are mentioned in the Product backlog\",\"HighlightContent_AR\":\"The Product backlog document has been created and passed to the UI Department to create aa UI With the features that are mentioned in the Product backlog\"},{\"HighlightId\":\"F980E882-CBF4-4AFB-6343-08DD2FDE285A\",\"HighlightName_EN\":\"UI\\/UX Design Done\",\"HighlightName_AR\":\"UI\\/UX Design Done\",\"HighlightCreatedAt\":\"2025-01-08T17:15:36.4514601\",\"HighlightContent_EN\":\"UI\\/UX Has been made and passed to the digital solution developer teams\",\"HighlightContent_AR\":\"UI\\/UX Has been made and passed to the digital solution developer teams\"}]"))







console.log(JSON.parse("[{\"MilestoneId\":\"DC66CB81-46DB-4595-8F15-08DD2FDE282B\",\"MilestoneName_EN\":\"Create a product backlog\",\"MilestoneName_AR\":\"Create a product backlog\",\"MilestoneDescription_EN\":\"A proper documentation of the proodcut being create dwill be made \",\"MilestoneDescription_AR\":\"A proper documentation of the proodcut being create dwill be made \",\"CompletionPercentage\":8.000000000000000e+001},{\"MilestoneId\":\"61BFFE3B-F87A-42C3-8F16-08DD2FDE282B\",\"MilestoneName_EN\":\"Create Figma for the UI\\/UX\",\"MilestoneName_AR\":\"Create Figma for the UI\\/UX\",\"MilestoneDescription_EN\":\"UI\\/UX Design will be createwd\",\"MilestoneDescription_AR\":\"UI\\/UX Design will be createwd\",\"CompletionPercentage\":1.000000000000000e+001},{\"MilestoneId\":\"6E619720-0F3D-45DC-8F17-08DD2FDE282B\",\"MilestoneName_EN\":\"Create the digital Solution\",\"MilestoneName_AR\":\"Create the digital Solution\",\"MilestoneDescription_EN\":\"Whole product must be created in this milestone\",\"MilestoneDescription_AR\":\"Whole product must be created in this milestone\",\"CompletionPercentage\":2.000000000000000e+001}]"))



console.log(JSON.parse("[{\"RiskLogId\":\"3BF4090E-E6E9-48E5-583C-08DD2FDE2832\",\"RiskLogDescription_EN\":\"Keeping a check on the progress of the proejct\",\"RiskLogDescription_AR\":\"Keeping a check on the progress of the proejct\",\"Likelihood\":\"{\\\"ColorClass\\\":\\\"green-tag\\\",\\\"Name_AR\\\":\\\"قليل\\\",\\\"Name_EN\\\":\\\"Low\\\"}\",\"Impact\":\"{\\\"ColorClass\\\":\\\"yellow-tag\\\",\\\"Name_AR\\\":\\\"واسطة\\\",\\\"Name_EN\\\":\\\"Medium\\\"}\",\"StatusLevel\":\"{\\\"ColorClass\\\":\\\"green-tag\\\",\\\"Name_AR\\\":\\\"قليل\\\",\\\"Name_EN\\\":\\\"Low\\\"}\"},{\"RiskLogId\":\"BA9CE72A-D62B-4F02-583D-08DD2FDE2832\",\"RiskLogDescription_EN\":\"Budget Issue may arise\",\"RiskLogDescription_AR\":\"Budget Issue may arise\",\"Likelihood\":\"{\\\"ColorClass\\\":\\\"yellow-tag\\\",\\\"Name_AR\\\":\\\"واسطة\\\",\\\"Name_EN\\\":\\\"Medium\\\"}\",\"Impact\":\"{\\\"ColorClass\\\":\\\"red-tag\\\",\\\"Name_AR\\\":\\\"عالي\\\",\\\"Name_EN\\\":\\\"High\\\"}\",\"StatusLevel\":\"{\\\"ColorClass\\\":\\\"yellow-tag\\\",\\\"Name_AR\\\":\\\"واسطة\\\",\\\"Name_EN\\\":\\\"Medium\\\"}\"}]"))

